// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGBsLk5kpOc1Jrl1yPlOn7p9ikAkV0as',
    appId: '1:790373541522:web:1ac2e928d47e9e24fda84b',
    messagingSenderId: '790373541522',
    projectId: 'mybiodata-app',
    authDomain: 'mybiodata-app.firebaseapp.com',
    storageBucket: 'mybiodata-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCE1cN0LXq_dxdbpKCiVGmDf_WV7DUX3Y',
    appId: '1:790373541522:android:f29f10769425b23ffda84b',
    messagingSenderId: '790373541522',
    projectId: 'mybiodata-app',
    storageBucket: 'mybiodata-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ6V450rILfW0MWmxdwCSHmfBoh99WoLs',
    appId: '1:790373541522:ios:ff38a4da12f8459bfda84b',
    messagingSenderId: '790373541522',
    projectId: 'mybiodata-app',
    storageBucket: 'mybiodata-app.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ6V450rILfW0MWmxdwCSHmfBoh99WoLs',
    appId: '1:790373541522:ios:ff38a4da12f8459bfda84b',
    messagingSenderId: '790373541522',
    projectId: 'mybiodata-app',
    storageBucket: 'mybiodata-app.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdGBsLk5kpOc1Jrl1yPlOn7p9ikAkV0as',
    appId: '1:790373541522:web:ee667d084ff3b51bfda84b',
    messagingSenderId: '790373541522',
    projectId: 'mybiodata-app',
    authDomain: 'mybiodata-app.firebaseapp.com',
    storageBucket: 'mybiodata-app.firebasestorage.app',
  );
}